#!/bin/bash

# Тестовый скрипт для проверки API Фазы 2
# Использование: ./test-api.sh

echo "🧪 Тестирование API SiteBuilder - Фаза 2"
echo "=========================================="
echo ""

BASE_URL="http://localhost:3000"

echo "1️⃣  Тест: Регистрация нового пользователя"
echo "POST /api/auth/register"
curl -s -X POST "${BASE_URL}/api/auth/register" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "Test User",
    "email": "test@example.com",
    "password": "test123"
  }' | jq '.'
echo ""
echo ""

echo "2️⃣  Тест: Получение списка шаблонов (публичный endpoint)"
echo "GET /api/templates"
curl -s "${BASE_URL}/api/templates" | jq 'length'
echo " шаблонов найдено"
echo ""
echo ""

echo "📝 Для тестирования защищенных endpoints:"
echo ""
echo "1. Запустите приложение: npm run dev"
echo "2. Войдите через браузер:"
echo "   - Администратор: admin@example.com / admin123"
echo "   - Редактор: editor@example.com / editor123"
echo "   - Наблюдатель: viewer@example.com / viewer123"
echo ""
echo "3. Тестирование через браузер консоль:"
echo ""
echo "// Получить список постов"
echo "fetch('/api/posts', { credentials: 'include' })"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""
echo "// Создать новый пост (ADMIN или EDITOR)"
echo "fetch('/api/posts', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  credentials: 'include',"
echo "  body: JSON.stringify({"
echo "    title: 'Новый пост',"
echo "    slug: 'new-post',"
echo "    content: 'Содержимое поста',"
echo "    published: true"
echo "  })"
echo "})"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""
echo "// Получить список медиафайлов"
echo "fetch('/api/media', { credentials: 'include' })"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""
echo "// Загрузить медиафайл (ADMIN или EDITOR)"
echo "fetch('/api/media', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  credentials: 'include',"
echo "  body: JSON.stringify({"
echo "    name: 'Тестовое изображение',"
echo "    fileName: 'test.jpg',"
echo "    url: 'https://via.placeholder.com/800x600',"
echo "    type: 'IMAGE',"
echo "    mimeType: 'image/jpeg',"
echo "    size: 100000,"
echo "    width: 800,"
echo "    height: 600,"
echo "    alt: 'Тестовое изображение'"
echo "  })"
echo "})"
echo "  .then(r => r.json())"
echo "  .then(console.log)"
echo ""
echo "✅ Доступные API endpoints:"
echo ""
echo "Посты:"
echo "  GET    /api/posts              - Список постов"
echo "  POST   /api/posts              - Создать пост"
echo "  GET    /api/posts/:id          - Получить пост"
echo "  PUT    /api/posts/:id          - Обновить пост"
echo "  DELETE /api/posts/:id          - Удалить пост"
echo ""
echo "Медиафайлы:"
echo "  GET    /api/media              - Список медиафайлов"
echo "  POST   /api/media              - Загрузить медиафайл"
echo "  GET    /api/media/:id          - Получить медиафайл"
echo "  PUT    /api/media/:id          - Обновить медиафайл"
echo "  DELETE /api/media/:id          - Удалить медиафайл"
echo ""
echo "📚 Документация:"
echo "  - API.md - Полная документация API"
echo "  - openapi.yaml - OpenAPI спецификация"
echo "  - PHASE2_IMPLEMENTATION.md - Отчет о реализации"
echo ""
